[tool.commitizen]
version = "0.2.0"
name = "cz_conventional_commits"
bump_message = "bump: version $current_version → $new_version [skip ci]"
tag_format = "$version"
version_scheme = "semver"
update_changelog_on_bump = true
version_files = [
    "Cargo.toml",
    "test_data/support_consensus/consensus_expected.vcf",
    "test_data/single_consensus/consensus_expected.vcf",
    "test_data/write_vcf.vcf",
]