[package]
name = "rundial"
version = "0.4.1"
edition = "2021"

[dependencies]
bio = "2.0.1"
clap = { version = "4.5.11", features = ["derive"] }
indexmap = "2.3.0"
niffler = "2.6.0"
ordered-float = "4.2.2"
phf = { version = "0.11.2", features = ["macros"]}
phf_macros = "0.11.2"
regex = "1.10.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.125"
serde_yaml = "0.9"
tempfile = "3.12.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
