[package]
name = "rundial"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
noodles = { version = "0.78.0", features = ["vcf"] }
phf = { version = "0.11.2", features = ["macros"]}
phf_macros = "0.11.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
vcf = "0.6.1"
