name: Build and Test
run-name: Build docker container and tests Nextflow
# This workflow allows for testing changes on a PR before being merged

on:
  workflow_dispatch:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker container
        run: |
          docker build -t test_container_rundial .
      - name: Inspect
        run: |
          docker image inspect test_container_rundial

      - name: Download Clair3 model
        run: |
          mkdir -p data/clair3_models
          wget \
            -O data/clair3_models/r1041_e82_400bps_sup_v430.tar.gz \
            https://cdn.oxfordnanoportal.com/software/analysis/models/clair3/r1041_e82_400bps_sup_v430.tar.gz

      - name: Run nf-test
        run: nf-test test tests/nextflow/*nf.test --profile local_docker
